seed: 99
net:
    arch: dpn92 # dpn68, dpn68b, dpn98, dpn131, dpn107
    kwargs:
        num_classes: 1000
 
dataset:
  train:
    image_dir: /mnt/lustre/share/images/train
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    image_dir: /mnt/lustre/share/images/val
    resize: 256
    center_crop: [224, 224]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 120
  test_freq: 1
  log_freq: 20
  optimizer:
    type: SGD
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1
 
saver:
  pretrian_model: 
  resume_model: 
  save_dir: checkpoints/dpn92   # save checkpoint locally
 
monitor:
  type: pavi
  _taskid: # continue training
  kwargs:
    project: default # change to your own pavi project
    task: dpn92
    model: dpn92
