seed: 99
net:
    arch: resnet50 # resnet18, resnet34, resnet50, resnet50c, resnet50d, resnet101, resnet101d, resnet152, resnet152d
                   # resnext50_32x4d, resnext101_32x8d, resnext50d_32x4d, resnext101d_32x8d
                   # wide_resnet50_2, wide_resnet101_2, wide_resnet50d_2, wide_resnet101d_2
    kwargs:
        num_classes: 1000
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    resize: 256
    center_crop: [224, 224]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 32 # resnet101 < 128
  workers: 4
 
trainer:
  max_epoch: 100
  test_freq: 1
  log_freq: 20
  optimizer:
    type: SGD
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1

saver:
  pretrain_model:
  resume_model:
  save_dir: checkpoints/resnet50   # save checkpoint locally
 
# monitor:
#   type: pavi
#   _taskid: # continue training
#   kwargs:
#     project: default  # change to your own pavi project
#     task: resnet50
#     model: resnet50
