seed: 99
net:
    arch: shuffle_v1
    kwargs:
        num_classes: 1000
        groups: 3
        in_channels: 3
        width_mult: 1
 
dataset:
  train:
    meta_file: /mnt/lustre/share/images/meta/train.txt
    image_dir: /mnt/lustre/share/images/train
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share/images/meta/val.txt
    image_dir: /mnt/lustre/share/images/val
    resize: 256
    center_crop: [224, 224]
    colorjitter:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: False
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 240
  test_freq: 1
  log_freq: 20
  optimizer:
    type: SGD
    kwargs:
      lr: 0.12
      momentum: 0.9
      weight_decay: 0.00004
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1
 
saver:
  pretrian_model: 
  resume_model: 
  save_dir: checkpoints/shuffle_v1   # save checkpoint locally
 
monitor:
  type: pavi
  _taskid: # continue training
  kwargs:
    project: default  # change to your own pavi project
    task: shuffle_v1_1x
    model: shuffle_v1_1x
