seed: 99
net:
    arch: dpn92
    kwargs:
        num_classes: 1000
 
dataset:
  train:
    meta_file: /mnt/lustre/share_data/parrots_algolib/datasets/Imagenet/meta/train.txt
    ceph_meta_file: s3://parrots_model_data/imagenet/images/meta/train.txt
    image_dir: /mnt/lustre/share_data/parrots_algolib/datasets/Imagenet/train
    ceph_image_dir: s3://parrots_model_data/imagenet/images/train/
    reader: pillow
    random_resize_crop: 224
    colorjitter: [0.2, 0.2, 0.2, 0.1]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    mirror: True
  test:
    meta_file: /mnt/lustre/share_data/parrots_algolib/datasets/Imagenet/meta/val.txt
    ceph_meta_file: s3://parrots_model_data/imagenet/images/meta/val.txt
    image_dir: /mnt/lustre/share_data/parrots_algolib/datasets/Imagenet/val
    ceph_image_dir: s3://parrots_model_data/imagenet/images/val/
    reader: pillow
    resize: 256
    center_crop: [224, 224]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  batch_size: 32
  workers: 4
 
trainer:
  max_epoch: 120
  test_freq: 2
  log_freq: 200
  label_smooth:
  optimizer:
    type: SGD
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    warmup_epochs: 0
    type: MultiStepLR
    kwargs:
      milestones: [30,60,90]
      gamma: 0.1
 
saver:
  # pretrian_model: 
  # resume_model: 
  # load_pavi:   # load pretrain/resume model from pavi
  # save_pavi: True   # add snapshot to pavi
  save_dir: algolib_gen/example/checkpoints/dpn92   # save checkpoint locally
  save_epoch_freq: 2
  save_latest: False
  save_best: True
 
# monitor:
  # type: pavi
  # kwargs:
  #   project: default
  #   task: dpn92
  #   model: dpn92
  # type: tensorboard
  # kwargs:
  #     logdir: tensorboard
